#!/bin/awk -f

function time_to_millis(t) {
    split(t, a, "[:.]")

    return a[1] * (3600 * 1000) + a[2] * (60 * 1000) + a[3] * 1000 + (a[4] + 0)
}

{
    sub(",", "", $(NF -2))
    print time_to_millis($1), $(NF-2), $NF
}
