#!/bin/awk -f

function file_exists(f,  cmd) {
    cmd = "test -e " f
    cmd | getline
    return ! close(cmd)
}

function abs(a) {
    return (a < 0) ? -a : a
}

function time_to_millis(t) {
    split(t, a, "[:.]")

    return a[1] * (3600 * 1000) + a[2] * (60 * 1000) + a[3] * 1000 + (a[4] + 0)
}

BEGIN {
    prog = PROCINFO["argv"][2]
    sub(".*/", "", prog)

    if (ARGC != 3) {
        print "Usage: " prog " file1 file2"
        exit 1
    }
    solved_file  = ARGV[1]
    log_file = ARGV[2]
    if (! file_exists(log_file))
        exit(1)

    n = split(solved_file, a, "-")
    coord = a[n]

    while (getline < solved_file) {
        solved[$1] = $2
    }
    close(solved_file)

    printf("# %-10s %-10s %-10s  %s\n", "millis", coord, "encoder", "radians")
    while (getline < log_file) {
        millis = $1; enc = $2; rad = $3
        for (m in solved) {
            if (abs(millis - m) <= 50) {
                printf("%-10d %10f %10d %25.20f\n", millis, solved[m], enc, rad)
                break
            }
        }
    }
}
